version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "${MINIFLUX_PORT}:8080"
    environment:
      - DATABASE_URL=postgres://${USER}@docker.for.mac.localhost/miniflux?sslmode=disable
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
